### ISSUE TITLE
cgroups v2 support

### ISSUE THREAD

**Issue by voltagex** [gsauthof/cgmemtime#4]
Could not mkdir /sys/fs/cgroup/memory/cgmemtime: No such file or directory - I'm assuming this means that many years later, this program is no longer compatible with the cgroups implementation in kernel 5.19. What would it take to update it?

**Comment by gsauthof** [comment]
The last time I checked the Cgroups v2 documentation, 6 years ago, and I gathered that it doesn't provide any high-water usage information, at all.

However, this seems to have change just a few months ago!

See: https://github.com/torvalds/linux/commit/8e20d4b332660a32e842e20c34cfc3b3456bc6dc

>   memory.peak
>	A read-only single value file which exists on non-root
>	cgroups.
>
>	The max memory usage recorded for the cgroup and its
>	descendants since the creation of the cgroup.

So once Kernel 5.19 hits my workstation I'll look into Cgroups v2 and how I can migrate cgmemtime to Cgroups v2.
